default_language_version:
  # force all unspecified python hooks to run python3
  python: python3

repos:
  - repo: local
    hooks:
      - id: pytest
        name: run tests
        entry: pytest
        language: system
        pass_filenames: false
        types: [python]
        # alternatively you could `types: [python]` so it only runs when python files change
        # though tests might be invalidated if you were to say change a data file
        always_run: true
